### ISSUE TITLE
findDependencies() method execution fails in generator when using .dep files

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#117]
When running my generators this time through, after having moved our .dep files to the correct location , I received this exception repeatedly:

ERROR: findDependencies() exception Unknown column 'artiface.merge_source' in 'where clause'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'artiface.merge_source' in 'where clause'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
        at com.pslcl.dtf.core.Core.findDependencies(Unknown Source)
        at com.pslcl.dtf.core.generator.Generator.findDependencies(Unknown Source)
        at com.pslcl.dtf.core.generator.resource.Machine.deploy(Unknown Source)
        at org.opendof.test.generator.util.Util.buildMachine(Unknown Source)
        at org.opendof.test.generator.oal.OperationsTestGenerator.main(Unknown Source)

it appears that the findDependencies() method has a typo in its where clause for the MySQL SQL statement, 'artiface.merge_source' column should be 'artifact.merge_source'.  It's located at line 1464 of com.pslcl.dtf.core.Core.java.

**Comment by jwclark** [comment]
Resolved.
