### ISSUE TITLE
Synchronize has multiple null pointer exceptions since commit ae83041

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#134]
When running synchronize any artifacts that use the findDependencies() method fail with a null pointer exception.  Also two other null pointer exceptions occasionally appear, which I believe may have to do with the findDependencies() null pointer issue.  The other two happen when synchronize tests and completing a test.  Here are the exception stack traces:

ERROR: findDependencies() exception null
java.lang.NullPointerException
        at com.pslcl.dtf.core.Core.findDependencies(Core.java:1436)
        at com.pslcl.dtf.core.generator.Generator.findDependencies(Generator.java:208)
        at com.pslcl.dtf.core.generator.resource.Machine.deploy(Machine.java:191)
        at com.pslcl.dtf.core.generator.resource.Machine.deploy(Machine.java:162)
        at org.opendof.test.generators.Util.prepMachine(Unknown Source)
        at org.opendof.test.generator.oal.OperationsTestGenerator.main(Unknown Source)
ERROR: Failure to sync test instances, null
java.lang.NullPointerException
        at com.pslcl.dtf.core.Core.check(Core.java:2279)
        at com.pslcl.dtf.core.Core.syncDescribedTemplates(Core.java:2336)
        at com.pslcl.dtf.core.generator.Generator.sync(Generator.java:386)
        at com.pslcl.dtf.core.generator.Generator.completeTest(Generator.java:351)
        at org.opendof.test.generator.oal.OperationsTestGenerator.main(Unknown Source)
ERROR: Failure to close generator, null
java.lang.NullPointerException
        at com.pslcl.dtf.core.Core.check(Core.java:2279)
        at com.pslcl.dtf.core.Core.syncDescribedTemplates(Core.java:2336)
        at com.pslcl.dtf.core.generator.Generator.sync(Generator.java:386)
        at com.pslcl.dtf.core.generator.Generator.close(Generator.java:441)
        at com.pslcl.dtf.core.generator.Generator.completeTest(Generator.java:357)
        at org.opendof.test.generator.oal.OperationsTestGenerator.main(Unknown Source)

**Comment by jwclark** [comment]
The generator was getting closed after the periodic syncs with the database added in that commit.
