### ISSUE TITLE
FatalServerTimeoutException when AWS instance comes up with no apparent errors

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#145]
After running 4 tests, two of them eventually failed with a FatalServerTimeoutException(stack trace below). One was linux, one was windows. Both instances came up in AWS and were not put into idle state after the tests failed:

23:39:30.113 WARN  [MachineInstanceFuture] c.p.d.resource.aws.ProgressiveDelay -
resourceId: 1
        manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
        provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
        templateId: 0xefbfbdefbfbdefbfbdefbfbdefbfbdefbfbd1000efbfbdefbfbd54c7b82eefbf
        templateInstanceId: 0
        runId: 1
message: null-ec2-0x0 stafPing
maxDelay: 5000 maxRetries: 17
totalTime: 1.0216666666666667min

com.pslcl.dtf.core.runner.resource.exception.FatalServerTimeoutException:
resourceId: 1
        manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
        provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
        templateId: 0xefbfbdefbfbdefbfbdefbfbdefbfbdefbfbd1000efbfbdefbfbd54c7b82eefbf
        templateInstanceId: 0
        runId: 1
message: null-ec2-0x0 stafPing
maxDelay: 5000 maxRetries: 17
totalTime: 1.0216666666666667min

        at com.pslcl.dtf.resource.aws.ProgressiveDelay.retry(ProgressiveDelay.java:108)
        at com.pslcl.dtf.resource.aws.ProgressiveDelay.retry(ProgressiveDelay.java:68)
        at com.pslcl.dtf.resource.aws.instance.machine.MachineInstanceFuture.waitForStaf(MachineInstanceFuture.java:311)
        at com.pslcl.dtf.resource.aws.instance.machine.MachineInstanceFuture.createInstance(MachineInstanceFuture.java:211)
        at com.pslcl.dtf.resource.aws.instance.machine.MachineInstanceFuture.call(MachineInstanceFuture.java:105)
        at com.pslcl.dtf.resource.aws.instance.machine.MachineInstanceFuture.call(MachineInstanceFuture.java:62)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jwclark** [comment]
[dtfrunner.log.2016-11-25.zip](https://github.com/PSLCL/testing-framework/files/613969/dtfrunner.log.2016-11-25.zip)
