### ISSUE TITLE
The portal fails to show any reports where there are a lot of test instances.

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#150]
It's difficult to queue up tests for modules or test plans when the portal fails to present the data in the various reports (module, and test plan).  This issue only happens when there is a large amount of test instances needing to be queried to create the report page for either the test plan or module report.  This is a critical bug and needs to be fixed.

It also appears to create heavy load on the RDS instance when trying to query these reports.  The CPU is high and is practically running at 100% for over 15 minutes.

This issue is related to issue #146 , though that issue was a Feature Request it now seems to cause a bug for any reports with large amounts of data, whether exporting to PDF or just trying to view the reports page from the portal.

**Comment by amauchley** [comment]
These are the two errors I'm seeing when trying to query a test plan report:

[chrome_console_log_tp.txt](https://github.com/PSLCL/testing-framework/files/632281/chrome_console_log_tp.txt)


I also see this from the node's server log:

GET /partials/test_plans/list.html 304 8ms
GET /api/v1/test_plans 304 15ms
GET /api/v1/test_plans 304 15ms
GET /api/v1/test_plans?offset=49 304 4ms
GET /api/v1/test_plans?offset=49 304 4ms
GET /api/v1/test_plans?offset=49 304 6ms
GET /api/v1/test_plans?offset=49 304 6ms
GET /api/v1/test_plans?offset=49 304 3ms
GET /api/v1/test_plans?offset=49 304 3ms
GET /api/v1/test_plans?offset=49 304 3ms
GET /api/v1/test_plans?offset=49 304 3ms
GET /api/v1/test_plans/9 304 10ms
GET /api/v1/test_plans/9 304 10ms
/home/ec2-user/testing-framework/portal/node_modules/mysql/lib/protocol/Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^

RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at ServerResponse.res.json (/home/ec2-user/testing-framework/portal/node_modules/express/lib/response.js:190:19)
    at ServerResponse.res.send (/home/ec2-user/testing-framework/portal/node_modules/express/lib/response.js:122:21)
    at Object.application/json (/home/ec2-user/testing-framework/portal/server/routes/instance.js:145:13)
    at ServerResponse.res.format (/home/ec2-user/testing-framework/portal/node_modules/express/lib/response.js:475:13)
    at /home/ec2-user/testing-framework/portal/server/routes/instance.js:140:9
    at Query._callback (/home/ec2-user/testing-framework/portal/server/models/instances.js:184:14)
    at Query.Sequence.end (/home/ec2-user/testing-framework/portal/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query._handleFinalResultPacket (/home/ec2-user/testing-framework/portal/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
error: Forever detected script exited with code: 1

HEAD /phpmyadmin/index.php 404 425ms - 2.75kb
HEAD /phpmyadmin/index.php 404 426ms - 2.75kb

404 error is a client error "NOT FOUND".


I should also say this is crashing node and forever is restarting the server over and over again when it crashes.

**Comment by amauchley** [comment]
Here is the chrome console log when trying to query a module report:

[chrome_console_log.txt](https://github.com/PSLCL/testing-framework/files/632261/chrome_console_log.txt)

**Comment by amauchley** [comment]
It may be worth looking at the query for the both types of reports to see if there is a way of performance improvement.  It may just be timing out with trying to get the information.
