### ISSUE TITLE
Log directory fails to be created by STAF

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#165]
Multiple tests are failing with a rc 10 STAFException error when trying to create the STDOUT log directories. This is the exception that is happening:

05:14:30.298 WARN  [RunEntryTask] c.p.dtf.runner.process.RunEntryCore - Failed to execute test run 1 - java.util.concurrent.ExecutionException: java.lang.Exception: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox/1/logs), OS RC: 17
java.util.concurrent.ExecutionException: java.lang.Exception: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox/1/logs), OS RC: 17
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.pslcl.dtf.runner.template.DeployHandler.waitComplete(DeployHandler.java:211)
        at com.pslcl.dtf.runner.template.DeployHandler.proceed(DeployHandler.java:178)
        at com.pslcl.dtf.runner.template.InstancedTemplate.runSteps(InstancedTemplate.java:632)
        at com.pslcl.dtf.runner.template.InstancedTemplate.<init>(InstancedTemplate.java:104)
        at com.pslcl.dtf.runner.template.TemplateProvider.getInstancedTemplate(TemplateProvider.java:272)
        at com.pslcl.dtf.runner.process.RunEntryCore.testRun(RunEntryCore.java:434)
        at com.pslcl.dtf.runner.process.Action$3.act(Action.java:83)
        at com.pslcl.dtf.runner.process.RunEntryTask.run(RunEntryTask.java:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox/1/logs), OS RC: 17
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.checkStafResult(StafSupport.java:313)
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.request(StafSupport.java:276)
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.issueProcessRequest(StafSupport.java:246)
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.issueProcessShellRequest(StafSupport.java:208)
        at com.pslcl.dtf.core.runner.resource.staf.futures.DeployFuture.executeStafProcess(DeployFuture.java:132)
        at com.pslcl.dtf.core.runner.resource.staf.futures.DeployFuture.call(DeployFuture.java:107)
        at com.pslcl.dtf.core.runner.resource.staf.futures.DeployFuture.call(DeployFuture.java:29)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 common frames omitted
Caused by: java.lang.RuntimeException: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox/1/logs), OS RC: 17
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.getResultRc(StafSupport.java:517)
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.checkStafResult(StafSupport.java:310)
        ... 10 common frames omitted
05:14:30.341 WARN  [RunEntryTask] com.pslcl.dtf.runner.process.Action - Action.TESTRUN() sees testRun() exception: java.util.concurrent.ExecutionException: java.lang.Exception: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox/1/logs), OS RC: 17

**Comment by amauchley** [comment]
Here is the debug log output for the various failure above:

20:52:54.362 DEBUG [RunEntryTask] c.p.d.runner.template.DeployHandler - DeployHandler waitComplete(), deploy failed future.get() with computed msg: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox/2695/logs), OS RC: $
20:52:54.362 DEBUG [RunEntryTask] c.p.d.r.template.InstancedTemplate - InstancedTemplate runSteps() errors out for templateID �^Z�����%��Ť������A_�h,^N�_��Ma�, templateInstanceID 4
20:52:54.362 DEBUG [RunEntryTask] c.p.d.r.template.TemplateProvider - TemplateProvider releaseTemplate() removes template �^Z�����%��Ť������A_�h,^N�_��Ma�, from templateReleaseMap, of templateInstanceID 4
20:52:54.363 DEBUG [RunEntryTask] c.p.d.r.template.TemplateProvider - TemplateProvider removeOneEntry_reusableTemplateList() finds 0 stored reusableITs, for templateHash: �^Z�����%��Ť������A_�h,^N�_��Ma�
20:52:54.363 DEBUG [RunEntryTask] c.p.d.r.template.TemplateProvider - TemplateProvider releaseTemplate() destroys template, for templateID �^Z�����%��Ť������A_�h,^N�_��Ma�, templateInstanceID 4
20:52:54.642 DEBUG [RunEntryTask] ConnectHandler - .disconnect() successfully disconects one machineInstance
20:52:54.939 DEBUG [RunEntryTask] ConnectHandler - .disconnect() successfully disconects one machineInstance
20:52:54.939 DEBUG [RunEntryTask] c.p.d.r.template.InstancedTemplate - InstancedTemplate informResourceProviders() about to inform the resource provider system that template �^Z�����%��Ť������A_�h,^N�_��Ma�, templateInstanceID 4 no longer needs its reserved or bo$
20:52:54.939 DEBUG [RunEntryTask] c.p.d.r.template.InstancedTemplate - InstancedTemplate informResourceProviders()        informed the resource provider system that template �^Z�����%��Ť������A_�h,^N�_��Ma�, templateInstanceID 4 no longer needs its reserved or bo$
20:52:54.939 DEBUG [RunEntryTask] c.p.dtf.runner.process.RunEntryCore - RunEntryCore testRun errors out, reNum : 2695
20:52:54.940 DEBUG [ReleaseNetworkFuture] c.p.d.r.a.p.n.ReleaseNetworkFuture - Releasing resource start:
resourceId: 15
        manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
        provider: com.pslcl.dtf.resource.aws.provider.network.AwsNetworkProvider
        templateId: 0xefbfbd1aefbfbdefbfbdefbfbdefbfbdefbfbd25efbfbdefbfbdc5a4efbfbdef
        templateInstanceId: 4
        runId: 2695

20:52:54.940 WARN  [RunEntryTask] c.p.dtf.runner.process.RunEntryCore - Failed to execute test run 2695 - java.util.concurrent.ExecutionException: java.lang.Exception: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox$
java.util.concurrent.ExecutionException: java.lang.Exception: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox/2695/logs), OS RC: 17
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.pslcl.dtf.runner.template.DeployHandler.waitComplete(DeployHandler.java:211)
        at com.pslcl.dtf.runner.template.DeployHandler.proceed(DeployHandler.java:178)
        at com.pslcl.dtf.runner.template.InstancedTemplate.runSteps(InstancedTemplate.java:632)
        at com.pslcl.dtf.runner.template.InstancedTemplate.<init>(InstancedTemplate.java:104)
        at com.pslcl.dtf.runner.template.TemplateProvider.getInstancedTemplate(TemplateProvider.java:272)
        at com.pslcl.dtf.runner.process.RunEntryCore.testRun(RunEntryCore.java:434)
        at com.pslcl.dtf.runner.process.Action$3.act(Action.java:83)
        at com.pslcl.dtf.runner.process.RunEntryTask.run(RunEntryTask.java:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox/2695/logs), OS RC: 17
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.checkStafResult(StafSupport.java:313)
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.request(StafSupport.java:276)
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.issueProcessRequest(StafSupport.java:246)
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.issueProcessShellRequest(StafSupport.java:208)
        at com.pslcl.dtf.core.runner.resource.staf.futures.DeployFuture.executeStafProcess(DeployFuture.java:132)
        at com.pslcl.dtf.core.runner.resource.staf.futures.DeployFuture.call(DeployFuture.java:107)
        at com.pslcl.dtf.core.runner.resource.staf.futures.DeployFuture.call(DeployFuture.java:29)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 common frames omitted
Caused by: java.lang.RuntimeException: StafException, rc: 10 (BaseOSError) result: Could not create STDOUT directory (/opt/dtf/sandbox/2695/logs), OS RC: 17
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.getResultRc(StafSupport.java:517)
        at com.pslcl.dtf.core.runner.resource.staf.StafSupport.checkStafResult(StafSupport.java:310)
        ... 10 common frames omitted
20:52:54.940 DEBUG [CancelTask] c.p.dtf.runner.process.CancelTask - CancelTask TERMINATES run-cancel checking for reNum 2695

**Comment by amauchley** [comment]
Here is the steps for runid 2695:

20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler Bind future.get()[1] returned at 2017-09-29 20:51:46
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler bind [1] completes, with attributes of {pslcl.dtf.aws.ec2instance.vpc.id=vpc-e7802f82, pslcl.dtf.aws.ec2instance.iam-arn=arn:aws:iam::406708278891:instance-profile/dtf-cst-iot-ser$
/usr/local/staf/startSTAFProc.sh}
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler Bind future.get()[2] called at 2017-09-29 20:51:46
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler Bind future.get()[2] returned at 2017-09-29 20:51:46
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler bind [2] completes, with attributes of {pslcl.dtf.aws.ec2instance.vpc.id=vpc-e7802f82, pslcl.dtf.aws.ec2instance.subnet.size=16, pslcl.dtf.aws.ec2instance.subnet.name=dtf-10.0.0.0$
20:51:46.093 DEBUG [RunEntryTask] c.p.d.r.template.InstancedTemplate - InstancedTemplate bindHandler() completes 3 bind(s) for setID 0
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 3, for step: 1 connect 0 2
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 4, for step: 1 connect 1 2
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 5, for step: 1 deploy 0 bin/SourceTest 9394A1EC8D7118335D132044CA19E7537D6F1555AFC90A123A563E91E3C495D0
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 6, for step: 1 deploy 0 cst-iot-test-testing-iot-service-1.3/bin/iot-service-1.3.txt 5B058762082906FB688385C39FC28AB8850F668F15BA4000264ABF999E7AF7EF
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 7, for step: 1 deploy 0 lib/libdof-data-transfer-common.a B7F7FD08B7B148F8573BCC4C88B5AEBDC74EEB4BB36C2F0224AD62EABAAC92DC
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 8, for step: 1 deploy 0 lib/libdof-data-transfer-common.so.2 72CC26BE1AD85B6D8E7CB12A452BA6DC1A6329DFD332D130618809CE20844C5B
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 9, for step: 1 deploy 0 lib/libdof-data-transfer-source.a F9A21C3298E0A091A9B00F913207C596B01597B5F6F2A0738C5EF4C30FF5A399
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 10, for step: 1 deploy 0 lib/libdof-data-transfer-source.so.2 00341188EA3DEFD5AEF1774D7EFD272722849DDEC6C2180E440D084C52FDE6CA
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 11, for step: 1 deploy 0 lib/libdof-inet.a 0159462F5092599578E2196CCD4D0B9B3048CF90767508D2C6098598E8B60CE8
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 12, for step: 1 deploy 0 lib/libdof-inet.so.2 D1BE8B0D0DB4DB3551E06590DB141851EB03D993C9C8B1D5E724A34CAFDF000F
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 13, for step: 1 deploy 0 lib/libdof-oal.a 970189270825C248CE66E7732521F1284D5B0D137CFBA7C8D202619BADBA7F3C
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 14, for step: 1 deploy 0 lib/libdof-oal.so.7 E4268CDBEA51CB777505C24B0706ACC0D254CD5590B39842A25AB4E6A482A55C
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 15, for step: 1 deploy 0 lib/libdof-pcr.a 7D8ADAABC834ACECB5E90603CE986DB85E1B0A2B637726B39708C498E5C865D9
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 16, for step: 1 deploy 0 lib/libdof-pcr.so.7 E12B417A8423BFF2B4C9AF9590EC9C5BDC8C96D5D9C5B555D7EDC43A82127D83
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 17, for step: 1 deploy 0 lib/libghthash.so.1 69BFB7BF6A0F8BF9FE7BDDFD3D5B08B0809489FCB8FEBD1E47B8A2B031DCFCCA
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 18, for step: 1 deploy 0 libexec/SourceTest 2CA37FAFB60643D9D2255919ED22D0662492AD9667274A39E19B909C5A4D29B9
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 19, for step: 1 deploy 1 bin/SinkTest A515C528289396A2E361FAAA08C322428CAE1D4B496E578E1481A6DDC327B03D
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 20, for step: 1 deploy 1 cst-iot-test-testing-iot-service-1.3/bin/iot-service-1.3.txt 5B058762082906FB688385C39FC28AB8850F668F15BA4000264ABF999E7AF7EF
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 21, for step: 1 deploy 1 lib/commons-logging-1.1.3.jar 70903F6FC82E9908C8DA9F20443F61D90F0870A312642991FE8462A0B9391784
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 22, for step: 1 deploy 1 lib/dof-data-transfer-common-2.0-2.0.jar 3CF0DBED7B534F3B664A278C609EB94FD327C99D252C3B2561195662856DDEAF
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 23, for step: 1 deploy 1 lib/dof-data-transfer-manager-2.0-2.0.jar 6DA48E3FED5F51D8C2D9BCDF4420FA4DAC2861C540DE0323865CE92A9CB112D8
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 24, for step: 1 deploy 1 lib/dof-data-transfer-sink-2.0.1.jar E30B16420B6454FC0BDFEE4886A93B296258849CB79D8647399A6D34AB05CF35
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 25, for step: 1 deploy 1 lib/dof-data-transfer-snapshot-2.0-2.0.jar 4291F578B1641D50B911E9A4759542573B4FC74BBEA385F009E6F1C92DA09F08
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 26, for step: 1 deploy 1 lib/dof-data-transfer-source-2.0.1.jar 7C8EB3C0B0B1E420687177C98D2B369CBB4EB1DCD8201531FAF0EDA0157492C6
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 27, for step: 1 deploy 1 lib/dof-inet-7.0.2.jar 22F8A9DFB66F7B834EA83C1364EC0F707A6158E75F494B6E2EE751354B2311EF
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 28, for step: 1 deploy 1 lib/dof-oal-7.0.5.jar CC84F5837ED24D1E9F228D10B7801DE7BCF45CC77984EF32D028BB2BFE803586
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 29, for step: 1 deploy 1 lib/logback-classic-1.1.7.jar A2C3919263DBF8CC7BB748B02588CB303254D3ACF9A81180B8F7727DA31677D9
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 30, for step: 1 deploy 1 lib/logback-core-1.1.7.jar A500AEDF2681FA4850E06698579140BB6233EE0E1878F98862B48CCCA4B2F1DE
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 31, for step: 1 deploy 1 lib/slf4j-api-1.7.21.jar 1D5AEB6BD98B0FDD151269EAE941C05F6468A791EA0F1E68D8E7FE518AF3E7DF
20:51:46.094 DEBUG [RunEntryTask] c.p.dtf.runner.template.StepsParser - StepsParser returns stepReference 32, for step: 1 deploy 1 lib/testing-dof-data-transfer-2.0.1.jar DD7AAE35820574C7E00F9A51E65EE2A0386E94734796BAA77AD443CA88D424B1
20:51:46.094 DEBUG [RunEntryTask] c.p.d.r.template.ConnectHandler - ConnectHandler computeConnectRequests() finds connect in stepSet 1: 1 connect 0 2
20:51:46.094 DEBUG [RunEntryTask] c.p.d.r.template.ConnectHandler - ConnectHandler computeConnectRequests() finds connect in stepSet 1: 1 connect 1 2
20:51:46.095 DEBUG [PingFuture] c.p.d.c.r.resource.staf.StafSupport - com.ibm.staf.STAFResult@1c79ee5dk] c.p.d.r.template.ConnectHandler - ConnectHan20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler Bind future.get()[1] returned $
20:51:46.093 DEBUG [RunEntryTask] c.p.dtf.runner.template.BindHandler - BindHandler bind [1] completes, with attributes of {pslcl.dtf.aws.ec2instance.vpc.id=vpc-e7802f82, pslcl.dtf.aws.ec2instance.iam-arn=arn:aws:iam::406708278891:instance-profile/dtf-cst-iot-ser$
/usr/local/staf/startSTAFProc.sh}

**Comment by Chad-Adams** [comment]
A couple of things are being tried here.
1. every stdout.log and stderr.log will now have a unique id added to the file names. stdoutN.log and stderrN.log where n is unique for the pair but the same value for the two files.
2.  ConfigureFuture will no longer create the stdout.log and stderr.log.
3.  DeleteFuture will no longer create the stdout.log and stderr.log.
4.  DeployFuture will no longer create the stdout.log and stderr.log.

Only RunFuture will create the stdoutN.log and stderrN.log files and cause them to copy to s3

**Comment by jwclark** [comment]
Should be fixed along with #164.
