### ISSUE TITLE
test machines may not clean up properly and are left running.

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#173]
At times it appears as if there were a lot of machines made, but what really happened was something went wrong with the cleanup of the machine resource and the node isn't terminated or put into a correct idle state. It's as if the machine can't be communicated too anymore by the dtfrunner service. So instead of ceasing the rest of the test executions the dtfrunner instantiates more needed machines, since to him the resource is dead. This is correct behavior, we don't want the runner to stop. Generally what happens in this sense is the machine is left up, the test run id is removed and the security group as well, but the machine remains up.  Related to issue #139 .

**Comment by jwclark** [comment]
On system startup, and periodically thereafter, we may want to query AWS for all machine/network resources with the system-Id tag set. Any resources that the resource provider doesn't know about, either because of a bug or because the system was previously shut down abrubtly, should be cleaned up.

We should also determine the cause for the machines not being properly cleaned up in the first place.

**Comment by amauchley** [comment]
Here is an info level warn log that may be connected to this cleanup issue:

20:36:37.125 WARN  [PslclBlockingExecutor-131] c.p.d.resource.aws.ProgressiveDelay -
resourceId: 59
        manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
        provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
        templateId: 0xefbfbdefbfbd0f6c51efbfbdefbfbdefbfbd76efbfbdefbfbdefbfbd03384569
        templateInstanceId: 19
        runId: 2497
message: null-eni-0x13 modifyInstanceAttribute

com.amazonaws.services.ec2.model.AmazonEC2Exception: You may only modify the groupSet attribute for VPC instances (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 7000e37c-d2e2-4275-b354-702ee19f7666)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:14329)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:14305)
        at com.amazonaws.services.ec2.AmazonEC2Client.executeModifyInstanceAttribute(AmazonEC2Client.java:11421)
        at com.amazonaws.services.ec2.AmazonEC2Client.modifyInstanceAttribute(AmazonEC2Client.java:11397)
        at com.pslcl.dtf.resource.aws.instance.machine.DisconnectFuture.call(DisconnectFuture.java:117)
        at com.pslcl.dtf.resource.aws.instance.machine.DisconnectFuture.call(DisconnectFuture.java:34)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
20:36:37.126 WARN  [RunEntryTask] ConnectHandler - .disconnect() fails to disconnect one machineInstance:
resourceId: 59
        manager: com.pslcl.dtf.resource.aws.AwsResourcesManager
        provider: com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider
        templateId: 0xefbfbdefbfbd0f6c51efbfbdefbfbdefbfbd76efbfbdefbfbdefbfbd03384569
        templateInstanceId: 19
        runId: 2497
message: null-eni-0x13 modifyInstanceAttribute
