### ISSUE TITLE
SetID 1 not fully successful, deploy handling error

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#176]
Numerous tests in the harness are failing to start completely due to this error.  I'm not for sure why it is happening, but by the exception it seems to be failing on one of the run steps.

Exception:

06:23:06.825 WARN  [RunEntryTask] c.p.dtf.runner.process.RunEntryCore - .testRun() failed to execute test run 21, throwable msg: java.lang.Exception: InstancedTemplate.runSteps() deploy handling for setID 1 not fully successful.
java.lang.Exception: InstancedTemplate.runSteps() deploy handling for setID 1 not fully successful.
        at com.pslcl.dtf.runner.template.InstancedTemplate.runSteps(InstancedTemplate.java:648)
        at com.pslcl.dtf.runner.template.InstancedTemplate.<init>(InstancedTemplate.java:104)
        at com.pslcl.dtf.runner.template.TemplateProvider.getInstancedTemplate(TemplateProvider.java:300)
        at com.pslcl.dtf.runner.process.RunEntryCore.testRun(RunEntryCore.java:433)
        at com.pslcl.dtf.runner.process.Action$3.act(Action.java:83)
        at com.pslcl.dtf.runner.process.RunEntryTask.run(RunEntryTask.java:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
06:23:06.839 WARN  [RunEntryTask] com.pslcl.dtf.runner.process.Action - Action.TESTRUN() sees testRun() throwable: java.lang.Exception: InstancedTemplate.runSteps() deploy handling for setID 1 not fully successful.
java.lang.Exception: InstancedTemplate.runSteps() deploy handling for setID 1 not fully successful.
        at com.pslcl.dtf.runner.template.InstancedTemplate.runSteps(InstancedTemplate.java:648)
        at com.pslcl.dtf.runner.template.InstancedTemplate.<init>(InstancedTemplate.java:104)
        at com.pslcl.dtf.runner.template.TemplateProvider.getInstancedTemplate(TemplateProvider.java:300)
        at com.pslcl.dtf.runner.process.RunEntryCore.testRun(RunEntryCore.java:433)
        at com.pslcl.dtf.runner.process.Action$3.act(Action.java:83)
        at com.pslcl.dtf.runner.process.RunEntryTask.run(RunEntryTask.java:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
		
		
		
Test run 21 Template steps:

0 bind machine pslcl.dtf.resource.machine.os=linux
0 bind machine pslcl.dtf.resource.machine.os=linux
0 bind network 
1 connect 0 2
1 connect 1 2
1 deploy 0 bin/OperationsTest 04DD53EE6E4FC9BD7420368955F44273654D8729A22D987F3FB9E7BE143997E2
1 deploy 0 lib/libdof-inet.a AC18072CA1BB41BA0C38817AE1FF93AE86A2AC8B3FCE3BDB0EA11CA6786464C5
1 deploy 0 lib/libdof-inet.so.2 1C35BCEFE453032F6BBD36F06CF69B31EB6D336BE61E30752A1190C8E5B3DE36
1 deploy 0 lib/libdof-oal.a 970189270825C248CE66E7732521F1284D5B0D137CFBA7C8D202619BADBA7F3C
1 deploy 0 lib/libdof-oal.so.7 E4268CDBEA51CB777505C24B0706ACC0D254CD5590B39842A25AB4E6A482A55C
1 deploy 0 lib/libdof-pcr.a 9C133DF62BF8AB5502638183DF2F89E36509579359921C116BBA7105B9EAB659
1 deploy 0 lib/libdof-pcr.so.7 B3A5C7B35C2C0257C10C15B1AAE8ED694EDC06CD53371595FE0969F603A090A1
1 deploy 0 libexec/OperationsTest 30D7EED11F71D78D42F0E39284C3F3C3BABDDB239F146A696022F2F86A2068EA
1 deploy 1 bin/OperationsTest 04DD53EE6E4FC9BD7420368955F44273654D8729A22D987F3FB9E7BE143997E2
1 deploy 1 lib/libdof-inet.a 0013FBAE308A7581891A39772050E792A3881E142775BF0E33D37635E04AA1DC
1 deploy 1 lib/libdof-inet.so.2 A79C12A51B8E5BD3BE4E68F06DB3598AF3C500E0373F74FF6AF76C58E2D2AC2F
1 deploy 1 lib/libdof-oal.a DF753129744DBE0F47EB869FF23D45022D31D22C6A0F8BA8072AFDF887DC1B4B
1 deploy 1 lib/libdof-oal.so.7 D334A4CF3EBE9E7D8881A572065EA067DF8655EE0A78F11A773B8E18552A8B73
1 deploy 1 lib/libdof-pcr.a 7D8ADAABC834ACECB5E90603CE986DB85E1B0A2B637726B39708C498E5C865D9
1 deploy 1 lib/libdof-pcr.so.7 E12B417A8423BFF2B4C9AF9590EC9C5BDC8C96D5D9C5B555D7EDC43A82127D83
1 deploy 1 libexec/OperationsTest C4D20A5933C59CD39AA4A672DC58C15C28A16162E4D538838AD8E24669B79982
2 start 0 bin%2FOperationsTest -providerMode -server -mcast
3 run 1 bin%2FOperationsTest -requestorMode -maxiterations 10 -address 224.0.23.46+-port+5567 -udp -stateless -testget

**Comment by jwclark** [comment]
This log indicates that one or more of the deploys failed. Were there any earlier log errors indicating that a deploy failed for this test?

**Comment by amauchley** [comment]
Nothing that I can see, it appears that is the only log output that comes out, at least for info level logging.  I'll try to run a debug level and see.
