### ISSUE TITLE
Resource terminated after reuse

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#182]
Start kill commands result in exception on staf process free command.

java.util.concurrent.ExecutionException: java.lang.Exception: StafException, rc: 12 (ProcessNotComplete) result: 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider.sanitizeInstance(AwsMachineProvider.java:461)
	at com.pslcl.dtf.resource.aws.provider.machine.AwsMachineProvider.release(AwsMachineProvider.java:361)
	at com.pslcl.dtf.resource.aws.AwsResourcesManager$ReleaseFuture.call(AwsResourcesManager.java:366)
	at com.pslcl.dtf.resource.aws.AwsResourcesManager$ReleaseFuture.call(AwsResourcesManager.java:332)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: StafException, rc: 12 (ProcessNotComplete) result: 
	at com.pslcl.dtf.core.runner.resource.staf.StafSupport.checkStafResult(StafSupport.java:313)
	at com.pslcl.dtf.core.runner.resource.staf.StafSupport.request(StafSupport.java:276)
	at com.pslcl.dtf.core.runner.resource.staf.StafSupport.processFree(StafSupport.java:111)
	at com.pslcl.dtf.core.runner.resource.staf.StafSupport.processStop(StafSupport.java:70)
	at com.pslcl.dtf.core.runner.resource.staf.futures.KillFuture.call(KillFuture.java:52)
	at com.pslcl.dtf.core.runner.resource.staf.futures.KillFuture.call(KillFuture.java:27)
	... 4 common frames omitted
Caused by: java.lang.RuntimeException: StafException, rc: 12 (ProcessNotComplete) result: 
	at com.pslcl.dtf.core.runner.resource.staf.StafSupport.getResultRc(StafSupport.java:517)
	at com.pslcl.dtf.core.runner.resource.staf.StafSupport.checkStafResult(StafSupport.java:310)
	... 9 common frames omitted

**Comment by jwclark** [comment]
non-fatal exception handling as temporary workaround. Ultimately we should find a way to correctly handle the ProcessNotComplete error returned by staf.
