### ISSUE TITLE
portal crashes when viewing test plan report

### ISSUE THREAD

**Issue by jwclark** [PSLCL/testing-framework#66]
call get_instance_list(1,null,null,"");

TypeError: Cannot call method 'split' of null
    at expandModules (/home/ec2-user/testing-framework/portal/server/routes/instance.js:98:17)
    at /home/ec2-user/testing-framework/portal/server/routes/instance.js:207:45
    at Function._.map._.collect (/home/ec2-user/testing-framework/portal/node_modules/underscore/underscore.js:172:24)
    at /home/ec2-user/testing-framework/portal/server/routes/instance.js:206:39
    at Function._.map._.collect (/home/ec2-user/testing-framework/portal/node_modules/underscore/underscore.js:172:24)
    at /home/ec2-user/testing-framework/portal/server/routes/instance.js:175:34
    at Function._.map._.collect (/home/ec2-user/testing-framework/portal/node_modules/underscore/underscore.js:172:24)
    at Query._callback (/home/ec2-user/testing-framework/portal/server/routes/instance.js:173:33)
    at Query.Sequence.end (/home/ec2-user/testing-framework/portal/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
    at Query._handleFinalResultPacket (/home/ec2-user/testing-framework/portal/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)

**Comment by jwclark** [comment]
Added null check to expandModules.
